services:
    entity_change_listener:
            class: Actiane\EntityChangeWatchBundle\Listener\EntityModificationListener
            arguments:
                - '%entity_watch.classes%'
                - '@service_container'
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postUpdate }
                - { name: doctrine.event_listener, event: postPersist }
                - { name: doctrine.event_listener, event: postDelete }