services:
    Actiane\EntityChangeWatchBundle\Listener\EntityModificationListener:
            autowire: false
            autoconfigure: false
            arguments:
                - '%entity_watch.classes%'
                - '@service_container'
                - '@property_accessor'
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postUpdate }
                - { name: doctrine.event_listener, event: postPersist }
                - { name: doctrine.event_listener, event: postDelete }