services:
    actiane.entitywatch.callback_locator:
        class: 'Symfony\Component\DependencyInjection\ServiceLocator'
        tags: ['container.service_locator']
    Actiane\EntityChangeWatchBundle\Generator\CallableGenerator:
        arguments:
            - '@actiane.entitywatch.callback_locator'
    Actiane\EntityChangeWatchBundle\Generator\LifecycleCallableGenerator:
        arguments:
            - '%entity_watch.classes%'
            - '@Actiane\EntityChangeWatchBundle\Generator\CallableGenerator'
            - '@property_accessor'
    Actiane\EntityChangeWatchBundle\Listener\EntityModificationListener:
            arguments:
                - '@Actiane\EntityChangeWatchBundle\Generator\LifecycleCallableGenerator'
            tags:
                - { name: doctrine.event_listener, event: onFlush }
                - { name: doctrine.event_listener, event: postFlush }
