services:
    Actiane\EntityChangeWatchBundle\Generator\CallableGenerator: ~
    Actiane\EntityChangeWatchBundle\Generator\LifecycleCallableGenerator:
        arguments:
            - '%entity_watch.classes%'
            - '@Actiane\EntityChangeWatchBundle\Generator\CallableGenerator'
            - '@property_accessor'
    Actiane\EntityChangeWatchBundle\Listener\EntityModificationListener:
            arguments:
                - '@Actiane\EntityChangeWatchBundle\Generator\LifecycleCallableGenerator'
            tags:
                - { name: doctrine.event_listener, event: onFlush }
                - { name: doctrine.event_listener, event: postFlush }
