sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t actiane/entity_change_watch .
  - docker run --mount type=bind,source="$(pwd)"/,target=/app actiane/entity_change_watch composer install
  - docker ps -a
  - docker run --mount type=bind,source="$(pwd)"/,target=/app actiane/entity_change_watch

script:
  - docker run --mount type=bind,source="$(pwd)"/,target=/app actiane/entity_change_watch