sudo: required

language: php

services:
  - docker

matrix:
  include:
    - env: SYMFONY_VERSION=2.7.*
    - env: SYMFONY_VERSION=2.8.*
    - env: SYMFONY_VERSION=3.0.*
    - env: SYMFONY_VERSION=3.1.*
    - env: SYMFONY_VERSION=3.2.*

before_install:
  - docker run --mount type=bind,source="$(pwd)"/,target=/app emilienpuget/entitychangewatch composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - docker run --mount type=bind,source="$(pwd)"/,target=/app emilienpuget/entitychangewatch composer install

script:
  - mkdir -p build/logs
  - docker run --mount type=bind,source="$(pwd)"/,target=/app emilienpuget/entitychangewatch vendor/bin/phpcs --ignore=*/vendor/*,*/build/*,*/Tests/* --standard=PSR2 .
  - docker run --mount type=bind,source="$(pwd)"/,target=/app emilienpuget/entitychangewatch vendor/bin/phpunit --configuration /app/phpunit.xml

after_success:
  travis_retry docker run -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID --mount type=bind,source="$(pwd)"/,target=/app emilienpuget/entitychangewatch php vendor/bin/php-coveralls -v
